"""Generate the torn-paper edges on the parchment boxes (.parch, .tatter) in template2.html.

Each box keeps its normal border and reads as an intact, darker page underneath; the lighter top page
is torn a few pixels inside it. This is an overlay (::after) that paints the torn-away margin in the
darker page colour, with a faint shadow line along the tear, so the content is never clipped.
Run:  py art/torn_edge.py  and paste the output over the "torn parchment edges" block in template2.html.
"""
import random
from urllib.parse import quote

rnd = random.Random(11)
L, D = 180, 7                 # tile length and margin depth in px
UNDER = '#9a7442'             # the intact darker page showing through the tear
SHADE = '#2a1404'             # shadow the top page casts onto the page below
LIGHT = '#f7e8c2'             # light catching the torn paper edge
pts, x = [], 0
while x < L:
    pts.append((x, 3 + (rnd.choice([0.3, 0.6, 0.9, 1.2, 1.6]) if rnd.random() < 0.92 else rnd.uniform(2.2, 3.0))))
    x += rnd.choice([3, 4, 5, 6])
pts.append((L, pts[0][1]))    # seamless: end where it started

def fmt(p): return 'L'.join(f'{x:g},{y:g}' for x, y in p)

def tile(fn, w, h, light_op=.85):
    """fn maps (along, depth-from-outer-edge) -> (x, y); fills the torn-away margin and shades the tear line"""
    line = [fn(a, d) for a, d in pts]
    shadow = [fn(a, d - 1.1) for a, d in pts]   # just outside the tear, on the page below
    area = 'M' + fmt([fn(0, 0)] + line + [fn(L, 0)]) + 'Z'
    s = (f"<svg xmlns='http://www.w3.org/2000/svg' width='{w}' height='{h}'>"
         f"<path d='{area}' fill='{UNDER}'/>"
         f"<path d='M{fmt(shadow)}' fill='none' stroke='{SHADE}' stroke-opacity='.55' stroke-width='1.6'/>"
         f"<path d='M{fmt(line)}' fill='none' stroke='{LIGHT}' stroke-opacity='{light_op}' stroke-width='.9'/></svg>")
    return 'url("data:image/svg+xml,' + quote(s, safe="/:=' ,.") + '")'

def layers(light_op):
    top = tile(lambda a, d: (a, d), L, D, light_op)
    bottom = tile(lambda a, d: (a, D - d), L, D, light_op)
    left = tile(lambda a, d: (d, a), D, L, light_op)
    right = tile(lambda a, d: (D - d, a), D, L, light_op)
    return ",".join([
        f"{top} top left/{L}px {D}px repeat-x",
        f"{bottom} bottom left/{L}px {D}px repeat-x",
        f"{left} top left/{D}px {L}px repeat-y",
        f"{right} top right/{D}px {L}px repeat-y",
    ])
print("/* torn parchment edges: generated by art/torn_edge.py */")
print(".parch,.tatter{position:relative}")
print(f".parch::after,.tatter::after{{content:\"\";position:absolute;inset:0;pointer-events:none;border-radius:inherit;background:{layers(.85)}}}")
# the darker parchment (Talent Order, Racials, Spellbook) gets a dimmer edge highlight so it doesn't glare
print(f".order-parch::after,#racials .parch::after,#spellbook .sb-page::after{{background:{layers(.3)}}}")
